.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CACHE901 1 "Jan 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
cache901 \- program for paperless geocaching
.SH SYNOPSIS
.B cache901
.RI [ options ] " files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B cache901
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBcache901\fP is a program for paperless geocaching.
It can download and locally store the informations needed for geocaching.
Log entriess can be entered while traveling for later upload.
.SH SEE ALSO
.BR gpsbabel (1).
.SH AUTHOR
cache901 was written by Michael J. Pedersen <m.pedersen@icelus.org>.
.PP
This manual page was written by Philipp Matthias Hahn <pmhahn@debian.org>,
for the Debian project (and may be used by others).

